/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import java.awt.Color;
import Database_Connector.Connector;
import java.util.Vector;
import javax.swing.*;
import java.io.File;
import org.json.simple.*;
import org.json.simple.parser.*;
import java.io.FileWriter;
import java.io.IOException;
import java.io.File;

/**
 *
 * @author HP
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    //
    public static Connector con;
    public static Vector<String> url_list = new Vector<>();
    public static Vector<String> name = new Vector<>();

    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Welcome_Scene = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        In_App_Scene = new javax.swing.JPanel();
        Head_panel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        season_lable = new javax.swing.JLabel();
        side_bar = new javax.swing.JPanel();
        sb_league_board = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        sb_schedule = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        sb_match_result = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        sb_team_search = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        sb_player_search = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        sb_match_update = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        Main_Panel = new javax.swing.JPanel();
        LeaderBoard = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lb_table = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        lb_roundchoose = new javax.swing.JComboBox<>();
        Schedule = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTableSchedule = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        Schedule_roundchoose = new javax.swing.JComboBox<>();
        Match_Result = new javax.swing.JPanel();
        mr_match_choose = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        mr_match_table = new javax.swing.JTable();
        mr_choose = new javax.swing.JLabel();
        mr_round = new javax.swing.JComboBox<>();
        mr_match_detail = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        rm_score = new javax.swing.JLabel();
        mr_hometeam = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        rm_hometeamxi = new javax.swing.JTextArea();
        mr_awayteam = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        rm_awayteamxi = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        rm_goalscorer = new javax.swing.JTextArea();
        rm_hometeamname = new javax.swing.JLabel();
        mr_awayteamname = new javax.swing.JLabel();
        mr_back = new javax.swing.JButton();
        Club_Search = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTableClubSearch = new javax.swing.JTable();
        jLabel24 = new javax.swing.JLabel();
        clubChoose = new javax.swing.JComboBox<>();
        Player_Search = new javax.swing.JPanel();
        PS_EnterKeywordTextField = new javax.swing.JTextField();
        PS_SearchForPlayerButton = new javax.swing.JButton();
        PS_InfoLable = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        footballPlayer = new javax.swing.JTable();
        Match_Update = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanel1.setLayout(new java.awt.CardLayout());

        Welcome_Scene.setBackground(new java.awt.Color(102, 0, 204));
        Welcome_Scene.setPreferredSize(new java.awt.Dimension(1280, 720));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Season Choose:");

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("START");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/images/logo_welcome.png"))); // NOI18N

        javax.swing.GroupLayout Welcome_SceneLayout = new javax.swing.GroupLayout(Welcome_Scene);
        Welcome_Scene.setLayout(Welcome_SceneLayout);
        Welcome_SceneLayout.setHorizontalGroup(
            Welcome_SceneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Welcome_SceneLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(596, 596, 596))
            .addGroup(Welcome_SceneLayout.createSequentialGroup()
                .addGroup(Welcome_SceneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Welcome_SceneLayout.createSequentialGroup()
                        .addGap(435, 435, 435)
                        .addComponent(jLabel2)
                        .addGap(34, 34, 34)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Welcome_SceneLayout.createSequentialGroup()
                        .addGap(303, 303, 303)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(305, Short.MAX_VALUE))
        );
        Welcome_SceneLayout.setVerticalGroup(
            Welcome_SceneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Welcome_SceneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(Welcome_SceneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(24, 24, 24)
                .addComponent(jButton1)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        jPanel1.add(Welcome_Scene, "card2");

        In_App_Scene.setBackground(new java.awt.Color(102, 0, 204));
        In_App_Scene.setPreferredSize(new java.awt.Dimension(1280, 720));

        Head_panel.setBackground(new java.awt.Color(102, 0, 204));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("VPL MANAGEMENT");

        season_lable.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        season_lable.setForeground(new java.awt.Color(255, 255, 255));
        season_lable.setText("SEASON: 2019 - 2020");

        javax.swing.GroupLayout Head_panelLayout = new javax.swing.GroupLayout(Head_panel);
        Head_panel.setLayout(Head_panelLayout);
        Head_panelLayout.setHorizontalGroup(
            Head_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Head_panelLayout.createSequentialGroup()
                .addContainerGap(139, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120)
                .addComponent(season_lable)
                .addGap(35, 35, 35))
        );
        Head_panelLayout.setVerticalGroup(
            Head_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Head_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Head_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                    .addGroup(Head_panelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(season_lable, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        side_bar.setBackground(new java.awt.Color(102, 0, 204));

        sb_league_board.setBackground(new java.awt.Color(102, 0, 204));
        sb_league_board.setPreferredSize(new java.awt.Dimension(186, 44));
        sb_league_board.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mouseclicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mouseentered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mouseexited(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("LeaderBoard");

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/images/icons8_leaderboard_30px.png"))); // NOI18N

        javax.swing.GroupLayout sb_league_boardLayout = new javax.swing.GroupLayout(sb_league_board);
        sb_league_board.setLayout(sb_league_boardLayout);
        sb_league_boardLayout.setHorizontalGroup(
            sb_league_boardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sb_league_boardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        sb_league_boardLayout.setVerticalGroup(
            sb_league_boardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
        );

        sb_schedule.setBackground(new java.awt.Color(102, 0, 204));
        sb_schedule.setPreferredSize(new java.awt.Dimension(297, 44));
        sb_schedule.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mouseclicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mouseentered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mouseexited(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Schedule");

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/images/icons8_schedule_32px.png"))); // NOI18N

        javax.swing.GroupLayout sb_scheduleLayout = new javax.swing.GroupLayout(sb_schedule);
        sb_schedule.setLayout(sb_scheduleLayout);
        sb_scheduleLayout.setHorizontalGroup(
            sb_scheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sb_scheduleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addContainerGap(164, Short.MAX_VALUE))
        );
        sb_scheduleLayout.setVerticalGroup(
            sb_scheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        sb_match_result.setBackground(new java.awt.Color(102, 0, 204));
        sb_match_result.setPreferredSize(new java.awt.Dimension(297, 44));
        sb_match_result.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mouseclicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mouseentered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mouseexited(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Match Result");

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/images/icons8_scoreboard_32px.png"))); // NOI18N

        javax.swing.GroupLayout sb_match_resultLayout = new javax.swing.GroupLayout(sb_match_result);
        sb_match_result.setLayout(sb_match_resultLayout);
        sb_match_resultLayout.setHorizontalGroup(
            sb_match_resultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sb_match_resultLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addContainerGap(128, Short.MAX_VALUE))
        );
        sb_match_resultLayout.setVerticalGroup(
            sb_match_resultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        sb_team_search.setBackground(new java.awt.Color(102, 0, 204));
        sb_team_search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mouseclicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mouseentered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mouseexited(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Club Search");

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/images/icons8_performance_24px.png"))); // NOI18N

        javax.swing.GroupLayout sb_team_searchLayout = new javax.swing.GroupLayout(sb_team_search);
        sb_team_search.setLayout(sb_team_searchLayout);
        sb_team_searchLayout.setHorizontalGroup(
            sb_team_searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sb_team_searchLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21)
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        sb_team_searchLayout.setVerticalGroup(
            sb_team_searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        sb_player_search.setBackground(new java.awt.Color(102, 0, 204));
        sb_player_search.setPreferredSize(new java.awt.Dimension(297, 44));
        sb_player_search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mouseclicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mouseentered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mouseexited(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Player Search");

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/images/icons8_jersey_24px.png"))); // NOI18N

        javax.swing.GroupLayout sb_player_searchLayout = new javax.swing.GroupLayout(sb_player_search);
        sb_player_search.setLayout(sb_player_searchLayout);
        sb_player_searchLayout.setHorizontalGroup(
            sb_player_searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sb_player_searchLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jLabel15)
                .addContainerGap(126, Short.MAX_VALUE))
        );
        sb_player_searchLayout.setVerticalGroup(
            sb_player_searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
        );

        sb_match_update.setBackground(new java.awt.Color(102, 0, 204));
        sb_match_update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mouseclicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mouseentered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mouseexited(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Match Update");

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/images/icons8_time_26px.png"))); // NOI18N

        javax.swing.GroupLayout sb_match_updateLayout = new javax.swing.GroupLayout(sb_match_update);
        sb_match_update.setLayout(sb_match_updateLayout);
        sb_match_updateLayout.setHorizontalGroup(
            sb_match_updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sb_match_updateLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel17)
                .addContainerGap(126, Short.MAX_VALUE))
        );
        sb_match_updateLayout.setVerticalGroup(
            sb_match_updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout side_barLayout = new javax.swing.GroupLayout(side_bar);
        side_bar.setLayout(side_barLayout);
        side_barLayout.setHorizontalGroup(
            side_barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sb_schedule, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
            .addComponent(sb_match_result, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
            .addComponent(sb_team_search, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(sb_player_search, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
            .addComponent(sb_match_update, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(sb_league_board, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
        );
        side_barLayout.setVerticalGroup(
            side_barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(side_barLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(sb_league_board, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(sb_schedule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(sb_match_result, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(sb_team_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(sb_player_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(sb_match_update, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Main_Panel.setBackground(new java.awt.Color(255, 153, 153));
        Main_Panel.setPreferredSize(new java.awt.Dimension(967, 533));
        Main_Panel.setLayout(new java.awt.CardLayout());

        LeaderBoard.setBackground(new java.awt.Color(102, 0, 204));
        LeaderBoard.setPreferredSize(new java.awt.Dimension(967, 533));

        lb_table.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9", "Title 10", "Title 11", "Title 12", "Title 13", "Title 14"
            }
        ));
        jScrollPane1.setViewportView(lb_table);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Round Choose:");

        lb_roundchoose.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lb_roundchoose.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                lb_roundchooseItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout LeaderBoardLayout = new javax.swing.GroupLayout(LeaderBoard);
        LeaderBoard.setLayout(LeaderBoardLayout);
        LeaderBoardLayout.setHorizontalGroup(
            LeaderBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeaderBoardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LeaderBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 947, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LeaderBoardLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_roundchoose, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        LeaderBoardLayout.setVerticalGroup(
            LeaderBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LeaderBoardLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(LeaderBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_roundchoose)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        Main_Panel.add(LeaderBoard, "card2");

        Schedule.setPreferredSize(new java.awt.Dimension(967, 533));

        jTableSchedule.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jScrollPane6.setViewportView(jTableSchedule);

        jLabel3.setText("Round");

        Schedule_roundchoose.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Schedule_roundchoose.setSelectedIndex(-1);
        Schedule_roundchoose.setSelectedItem(null);
        Schedule_roundchoose.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Schedule_roundchooseItemStateChanged(evt);
            }
        });
        Schedule_roundchoose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Schedule_roundchooseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ScheduleLayout = new javax.swing.GroupLayout(Schedule);
        Schedule.setLayout(ScheduleLayout);
        ScheduleLayout.setHorizontalGroup(
            ScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ScheduleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 907, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ScheduleLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(Schedule_roundchoose, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(223, 223, 223))
        );
        ScheduleLayout.setVerticalGroup(
            ScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ScheduleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Schedule_roundchoose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Main_Panel.add(Schedule, "card3");

        Match_Result.setPreferredSize(new java.awt.Dimension(967, 533));
        Match_Result.setLayout(new java.awt.CardLayout());

        mr_match_choose.setBackground(new java.awt.Color(102, 0, 204));

        mr_match_table.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        mr_match_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        mr_match_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mr_match_tableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(mr_match_table);

        mr_choose.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        mr_choose.setForeground(new java.awt.Color(255, 255, 255));
        mr_choose.setText("Round:");

        mr_round.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        mr_round.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                mr_roundItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout mr_match_chooseLayout = new javax.swing.GroupLayout(mr_match_choose);
        mr_match_choose.setLayout(mr_match_chooseLayout);
        mr_match_chooseLayout.setHorizontalGroup(
            mr_match_chooseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mr_match_chooseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 947, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mr_match_chooseLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mr_choose)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mr_round, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        mr_match_chooseLayout.setVerticalGroup(
            mr_match_chooseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mr_match_chooseLayout.createSequentialGroup()
                .addContainerGap(97, Short.MAX_VALUE)
                .addGroup(mr_match_chooseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mr_choose, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mr_round, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        Match_Result.add(mr_match_choose, "card2");

        mr_match_detail.setBackground(new java.awt.Color(102, 0, 204));
        mr_match_detail.setForeground(new java.awt.Color(255, 255, 255));
        mr_match_detail.setFocusable(false);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel6.setText("FULL TIME");

        rm_score.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        rm_score.setText("5 - 5");

        mr_hometeam.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Home Team XI", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N

        rm_hometeamxi.setColumns(20);
        rm_hometeamxi.setRows(5);
        jScrollPane3.setViewportView(rm_hometeamxi);

        javax.swing.GroupLayout mr_hometeamLayout = new javax.swing.GroupLayout(mr_hometeam);
        mr_hometeam.setLayout(mr_hometeamLayout);
        mr_hometeamLayout.setHorizontalGroup(
            mr_hometeamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mr_hometeamLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                .addContainerGap())
        );
        mr_hometeamLayout.setVerticalGroup(
            mr_hometeamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mr_hometeamLayout.createSequentialGroup()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );

        mr_awayteam.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Away Team XI", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N

        rm_awayteamxi.setColumns(20);
        rm_awayteamxi.setRows(5);
        jScrollPane4.setViewportView(rm_awayteamxi);

        javax.swing.GroupLayout mr_awayteamLayout = new javax.swing.GroupLayout(mr_awayteam);
        mr_awayteam.setLayout(mr_awayteamLayout);
        mr_awayteamLayout.setHorizontalGroup(
            mr_awayteamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mr_awayteamLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                .addContainerGap())
        );
        mr_awayteamLayout.setVerticalGroup(
            mr_awayteamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mr_awayteamLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Goal Scorer", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N

        rm_goalscorer.setColumns(20);
        rm_goalscorer.setRows(5);
        jScrollPane5.setViewportView(rm_goalscorer);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5)
                .addContainerGap())
        );

        rm_hometeamname.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        rm_hometeamname.setForeground(new java.awt.Color(255, 255, 255));
        rm_hometeamname.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        rm_hometeamname.setText("jLabel24");

        mr_awayteamname.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        mr_awayteamname.setForeground(new java.awt.Color(255, 255, 255));
        mr_awayteamname.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        mr_awayteamname.setText("jLabel24");

        mr_back.setText("BACK");
        mr_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mr_backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mr_match_detailLayout = new javax.swing.GroupLayout(mr_match_detail);
        mr_match_detail.setLayout(mr_match_detailLayout);
        mr_match_detailLayout.setHorizontalGroup(
            mr_match_detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mr_match_detailLayout.createSequentialGroup()
                .addGroup(mr_match_detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mr_match_detailLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(mr_match_detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mr_match_detailLayout.createSequentialGroup()
                                .addComponent(mr_back, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(297, 297, 297)
                                .addComponent(jLabel6)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(mr_match_detailLayout.createSequentialGroup()
                                .addComponent(rm_hometeamname, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(rm_score)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(mr_awayteamname, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(mr_match_detailLayout.createSequentialGroup()
                        .addComponent(mr_hometeam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(mr_awayteam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        mr_match_detailLayout.setVerticalGroup(
            mr_match_detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mr_match_detailLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mr_match_detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(mr_back))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mr_match_detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mr_match_detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rm_hometeamname)
                        .addComponent(mr_awayteamname))
                    .addComponent(rm_score))
                .addGap(58, 58, 58)
                .addGroup(mr_match_detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mr_hometeam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mr_awayteam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        Match_Result.add(mr_match_detail, "card3");

        Main_Panel.add(Match_Result, "card4");

        Club_Search.setPreferredSize(new java.awt.Dimension(967, 533));

        jTableClubSearch.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane7.setViewportView(jTableClubSearch);

        jLabel24.setText("List Club");

        clubChoose.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        clubChoose.setSelectedIndex(-1);
        clubChoose.setSelectedItem(null);
        clubChoose.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                clubChooseItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout Club_SearchLayout = new javax.swing.GroupLayout(Club_Search);
        Club_Search.setLayout(Club_SearchLayout);
        Club_SearchLayout.setHorizontalGroup(
            Club_SearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Club_SearchLayout.createSequentialGroup()
                .addGap(488, 488, 488)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(clubChoose, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Club_SearchLayout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 833, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101))
        );
        Club_SearchLayout.setVerticalGroup(
            Club_SearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Club_SearchLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(Club_SearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clubChoose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(111, Short.MAX_VALUE))
        );

        Main_Panel.add(Club_Search, "card5");

        Player_Search.setPreferredSize(new java.awt.Dimension(967, 533));

        PS_EnterKeywordTextField.setText("Enter Keywords related to Player");
        PS_EnterKeywordTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PS_EnterKeywordTextFieldActionPerformed(evt);
            }
        });

        PS_SearchForPlayerButton.setText("Search for player");
        PS_SearchForPlayerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PS_SearchForPlayerButtonActionPerformed(evt);
            }
        });

        PS_InfoLable.setText("FOOTBALL PLAYER SEARCH ENGINE VER 1995.213123.656345.34");

        footballPlayer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PlayerID", "Name", "ClubID", "Nationality", "Birthday", "Position", "Salary", "Address", "HireDate", "ExpirationDate"
            }
        ));
        jScrollPane8.setViewportView(footballPlayer);

        javax.swing.GroupLayout Player_SearchLayout = new javax.swing.GroupLayout(Player_Search);
        Player_Search.setLayout(Player_SearchLayout);
        Player_SearchLayout.setHorizontalGroup(
            Player_SearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Player_SearchLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(PS_InfoLable, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(182, 182, 182))
            .addGroup(Player_SearchLayout.createSequentialGroup()
                .addGap(293, 293, 293)
                .addComponent(PS_EnterKeywordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(PS_SearchForPlayerButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Player_SearchLayout.createSequentialGroup()
                .addContainerGap(92, Short.MAX_VALUE)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 834, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
        Player_SearchLayout.setVerticalGroup(
            Player_SearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Player_SearchLayout.createSequentialGroup()
                .addComponent(PS_InfoLable, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Player_SearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PS_EnterKeywordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PS_SearchForPlayerButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        Main_Panel.add(Player_Search, "card6");

        Match_Update.setPreferredSize(new java.awt.Dimension(967, 533));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Select round file:");

        jTextField1.setEditable(false);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Update");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Match_UpdateLayout = new javax.swing.GroupLayout(Match_Update);
        Match_Update.setLayout(Match_UpdateLayout);
        Match_UpdateLayout.setHorizontalGroup(
            Match_UpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Match_UpdateLayout.createSequentialGroup()
                .addGap(211, 211, 211)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Match_UpdateLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(368, 368, 368))
        );
        Match_UpdateLayout.setVerticalGroup(
            Match_UpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Match_UpdateLayout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addGroup(Match_UpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addContainerGap(355, Short.MAX_VALUE))
        );

        Main_Panel.add(Match_Update, "card7");

        jPanel2.setBackground(new java.awt.Color(102, 0, 204));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/images/adsfasdf-removebg.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel16)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout In_App_SceneLayout = new javax.swing.GroupLayout(In_App_Scene);
        In_App_Scene.setLayout(In_App_SceneLayout);
        In_App_SceneLayout.setHorizontalGroup(
            In_App_SceneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(In_App_SceneLayout.createSequentialGroup()
                .addGroup(In_App_SceneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(side_bar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(In_App_SceneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Head_panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Main_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        In_App_SceneLayout.setVerticalGroup(
            In_App_SceneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(In_App_SceneLayout.createSequentialGroup()
                .addGroup(In_App_SceneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Head_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(In_App_SceneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Main_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(side_bar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel1.add(In_App_Scene, "card3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mouseentered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseentered
        // TODO add your handling code here:
        if (evt.getSource() == sb_league_board) {
            sb_league_board.setBackground(new Color(102, 0, 153));
        }
        if (evt.getSource() == sb_schedule) {
            sb_schedule.setBackground(new Color(102, 0, 153));
        }
        if (evt.getSource() == sb_match_result) {
            sb_match_result.setBackground(new Color(102, 0, 153));
        }
        if (evt.getSource() == sb_match_update) {
            sb_match_update.setBackground(new Color(102, 0, 153));
        }
        if (evt.getSource() == sb_player_search) {
            sb_player_search.setBackground(new Color(102, 0, 153));
        }
        if (evt.getSource() == sb_team_search) {
            sb_team_search.setBackground(new Color(102, 0, 153));
        }
    }//GEN-LAST:event_mouseentered

    private void mouseexited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseexited
        // TODO add your handling code here:
        if (evt.getSource() == sb_league_board) {
            sb_league_board.setBackground(new Color(102, 0, 204));
        }
        if (evt.getSource() == sb_schedule) {
            sb_schedule.setBackground(new Color(102, 0, 204));
        }
        if (evt.getSource() == sb_match_result) {
            sb_match_result.setBackground(new Color(102, 0, 204));
        }
        if (evt.getSource() == sb_match_update) {
            sb_match_update.setBackground(new Color(102, 0, 204));
        }
        if (evt.getSource() == sb_player_search) {
            sb_player_search.setBackground(new Color(102, 0, 204));
        }
        if (evt.getSource() == sb_team_search) {
            sb_team_search.setBackground(new Color(102, 0, 204));
        }
    }//GEN-LAST:event_mouseexited

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int index = jComboBox1.getSelectedIndex();
        
        if(index>=url_list.size()){
            JFileChooser chooser = new JFileChooser();
            chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
            int option = chooser.showOpenDialog(new JFrame());
            if (option == JFileChooser.APPROVE_OPTION) {
                File file = chooser.getSelectedFile();
                String path = file.getAbsolutePath();
                String season = new Database().new_database(path);
                String url = "jdbc:mysql://localhost:3306/vpl"+season;
                season = season.replace('_', '-');
                season_lable.setText("SEASON: "+season);
                JSONObject ob = new JSONObject();
                JSONArray arr = new JSONArray();
                for(int i=0;i<name.size()-1;i++){
                    JSONObject temp = new JSONObject();
                    temp.put("name", name.elementAt(i));
                    temp.put("url",url_list.elementAt(i));
                    arr.add(temp);
                }
                JSONObject temp = new JSONObject();
                temp.put("name", season);
                temp.put("url", url);
                arr.add(temp);
                ob.put("Season", arr);
                try {
                    // Constructs a FileWriter given a file name, using the platform's default charset
                    FileWriter file1 = new FileWriter("C:\\Users\\HP\\Desktop\\database\\season.json");
                    file1.write(ob.toJSONString());
                    file1.flush();
                    file1.close();

                } catch (IOException e) {
                    e.printStackTrace();

                } 
                System.out.println(url);
                con = new Connector(url);
            }
        }else{
            con = new Connector(url_list.elementAt(index));
            season_lable.setText("SEASON: "+name.elementAt(index));
        }
        In_App_Scene.setVisible(true);
        Welcome_Scene.setVisible(false);
        new Leader_Board().LB_Start(con, lb_roundchoose);
        new Match_Result().MR_Start(mr_round, con);
        new Schedule().scheduleStart(con, Schedule_roundchoose);
        new ClubSearch().clubSearchStart(con, clubChoose);
        //new MatchUpdate().MatchUpdateStart(con, MatchUpdate_roundchoose);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void mouseclicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseclicked
        // TODO add your handling code here:
        if (evt.getSource() == sb_league_board) {
            LeaderBoard.setVisible(true);
            Schedule.setVisible(false);
            Match_Result.setVisible(false);
            Match_Update.setVisible(false);
            Player_Search.setVisible(false);
            Club_Search.setVisible(false);
            new Leader_Board().LB_Start(con, lb_roundchoose);
        }
        if (evt.getSource() == sb_schedule) {
            LeaderBoard.setVisible(false);
            Schedule.setVisible(true);
            Match_Result.setVisible(false);
            Match_Update.setVisible(false);
            Player_Search.setVisible(false);
            Club_Search.setVisible(false);
            new Schedule().scheduleStart(con, Schedule_roundchoose);
        }
        if (evt.getSource() == sb_match_result) {
            LeaderBoard.setVisible(false);
            Schedule.setVisible(false);
            Match_Result.setVisible(true);
            Match_Update.setVisible(false);
            Player_Search.setVisible(false);
            Club_Search.setVisible(false);
            new Match_Result().MR_Start(mr_round, con);
        }
        if (evt.getSource() == sb_match_update) {
            LeaderBoard.setVisible(false);
            Schedule.setVisible(false);
            Match_Result.setVisible(false);
            Match_Update.setVisible(true);
            Player_Search.setVisible(false);
            Club_Search.setVisible(false);
        }
        if (evt.getSource() == sb_player_search) {
            LeaderBoard.setVisible(false);
            Schedule.setVisible(false);
            Match_Result.setVisible(false);
            Match_Update.setVisible(false);
            Player_Search.setVisible(true);
            Club_Search.setVisible(false);
        }
        if (evt.getSource() == sb_team_search) {
            LeaderBoard.setVisible(false);
            Schedule.setVisible(false);
            Match_Result.setVisible(false);
            Match_Update.setVisible(false);
            Player_Search.setVisible(false);
            Club_Search.setVisible(true);
            new ClubSearch().clubSearchStart(con, clubChoose);
        }
    }//GEN-LAST:event_mouseclicked

    private void lb_roundchooseItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_lb_roundchooseItemStateChanged
        // TODO add your handling code here:
        new Leader_Board().Load_LB(con, Integer.parseInt(lb_roundchoose.getSelectedItem().toString()), lb_table);
    }//GEN-LAST:event_lb_roundchooseItemStateChanged

    private void mr_roundItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_mr_roundItemStateChanged
        // TODO add your handling code here:
        new Match_Result().Round_Choose(mr_match_table, Integer.parseInt(mr_round.getSelectedItem().toString()), con);
    }//GEN-LAST:event_mr_roundItemStateChanged

    private void mr_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mr_backActionPerformed
        // TODO add your handling code here:
        mr_match_choose.setVisible(true);
        mr_match_detail.setVisible(false);
    }//GEN-LAST:event_mr_backActionPerformed

    private void mr_match_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mr_match_tableMouseClicked
        // TODO add your handling code here:
        int index = mr_match_table.getSelectedRow();
        String math_id = mr_match_table.getModel().getValueAt(index, 0).toString();
        String home_name = mr_match_table.getModel().getValueAt(index, 1).toString();
        String away_name = mr_match_table.getModel().getValueAt(index, 2).toString();
        rm_score.setText(mr_match_table.getModel().getValueAt(index, 3).toString());
        rm_hometeamname.setText(home_name);
        mr_awayteamname.setText(away_name);
        new Match_Result().Match_Detail(con, math_id, home_name, away_name, rm_hometeamxi, rm_awayteamxi, rm_goalscorer);
        mr_match_choose.setVisible(false);
        mr_match_detail.setVisible(true);
    }//GEN-LAST:event_mr_match_tableMouseClicked

    private void Schedule_roundchooseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Schedule_roundchooseActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_Schedule_roundchooseActionPerformed

    private void Schedule_roundchooseItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Schedule_roundchooseItemStateChanged
        // TODO add your handling code here:
        new Schedule().loadDataMatchGame(con, jTableSchedule, Integer.parseInt(Schedule_roundchoose.getSelectedItem().toString()));
    }//GEN-LAST:event_Schedule_roundchooseItemStateChanged

    private void clubChooseItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_clubChooseItemStateChanged
        // TODO add your handling code here:
        new ClubSearch().loadDataClubCManaCoachStadium(con, jTableClubSearch, clubChoose.getSelectedItem().toString());
    }//GEN-LAST:event_clubChooseItemStateChanged

    private void PS_EnterKeywordTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PS_EnterKeywordTextFieldActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_PS_EnterKeywordTextFieldActionPerformed

    private void PS_SearchForPlayerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PS_SearchForPlayerButtonActionPerformed
        // TODO add your handling code here:
        //phần code
        new PlayerSearch().loadDatabase(con, footballPlayer, PS_EnterKeywordTextField.getText().toString());
    }//GEN-LAST:event_PS_SearchForPlayerButtonActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int option = chooser.showOpenDialog(new JFrame());
        if (option == JFileChooser.APPROVE_OPTION) {
            File file = chooser.getSelectedFile();
            String path = file.getAbsolutePath();
            jTextField1.setText(path);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String temp = jTextField1.getText();
        if(temp==""){
            return;
        }
        new MatchUpdate().round_update(temp, con);
        jTextField1.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
                new Database().load_season(url_list, name);
                for(int i=0;i<name.size();i++){
                    jComboBox1.addItem(name.elementAt(i));
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Club_Search;
    private javax.swing.JPanel Head_panel;
    private static javax.swing.JPanel In_App_Scene;
    private javax.swing.JPanel LeaderBoard;
    private javax.swing.JPanel Main_Panel;
    private javax.swing.JPanel Match_Result;
    private javax.swing.JPanel Match_Update;
    private javax.swing.JTextField PS_EnterKeywordTextField;
    private javax.swing.JLabel PS_InfoLable;
    private javax.swing.JButton PS_SearchForPlayerButton;
    private javax.swing.JPanel Player_Search;
    private javax.swing.JPanel Schedule;
    private static javax.swing.JComboBox<String> Schedule_roundchoose;
    private static javax.swing.JPanel Welcome_Scene;
    private static javax.swing.JComboBox<String> clubChoose;
    private javax.swing.JTable footballPlayer;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private static javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTable jTableClubSearch;
    private javax.swing.JTable jTableSchedule;
    private javax.swing.JTextField jTextField1;
    private static javax.swing.JComboBox<String> lb_roundchoose;
    private javax.swing.JTable lb_table;
    private javax.swing.JPanel mr_awayteam;
    private javax.swing.JLabel mr_awayteamname;
    private javax.swing.JButton mr_back;
    private javax.swing.JLabel mr_choose;
    private javax.swing.JPanel mr_hometeam;
    private javax.swing.JPanel mr_match_choose;
    private javax.swing.JPanel mr_match_detail;
    private javax.swing.JTable mr_match_table;
    private static javax.swing.JComboBox<String> mr_round;
    private javax.swing.JTextArea rm_awayteamxi;
    private javax.swing.JTextArea rm_goalscorer;
    private javax.swing.JLabel rm_hometeamname;
    private javax.swing.JTextArea rm_hometeamxi;
    private javax.swing.JLabel rm_score;
    private javax.swing.JPanel sb_league_board;
    private javax.swing.JPanel sb_match_result;
    private javax.swing.JPanel sb_match_update;
    private javax.swing.JPanel sb_player_search;
    private javax.swing.JPanel sb_schedule;
    private javax.swing.JPanel sb_team_search;
    private javax.swing.JLabel season_lable;
    private javax.swing.JPanel side_bar;
    // End of variables declaration//GEN-END:variables
}
